name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What's Changed

  $CHANGES

categories:
  - title: "💥 Breaking changes"
    label: "breaking change"
  - title: "🚀 Features"
    label: feature
  - title: "☘️ Change specs"
    label: change
  - title: "🐛 Bug Fixes"
    label: bug
  - title: "📝 Chore"
    label: chore
  - title: "🎨 Renovate"
    label: renovate

version-resolver:
  major:
    labels:
      - "breaking change"
  minor:
    labels:
      - feature
      - change
  patch:
    labels:
      - bug
      - chore
      - renovate
  default: patch

autolabeler:
  - label: "breaking change"
    branch:
      - '/breaking\/.+/'
  - label: feature
    branch:
      - '/feature\/.+/'
  - label: change
    branch:
      - '/change\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: renovate
    branch:
      - '/renovate\/.+/'
