name: Publish Release

on:
  workflow_dispatch:

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
      - name: yarn install
        run: |
          corepack enable
          yarn install --immutable
      - uses: release-drafter/release-drafter@v6
        id: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: bump version
        run: |
          npm version "${{ steps.release_drafter.outputs.tag_name }}" --git-tag-version false
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m ":bookmark: version bump"
          git push
          yarn build
      - uses: release-drafter/release-drafter@v6
        id: release_drafter_publish
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: dist.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.release_drafter_publish.outputs.tag_name }}
