name: Publish Release

on:
  workflow_dispatch:

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "New version: ${{ steps.release_drafter.outputs.tag }}"

      # - uses: actions/checkout@v2
      # - name: bump version
      #   run: |
      #     npm version ${{ steps.release_drafter.outputs.tag }} -m ":bookmark: version bump"
      # - uses: release-drafter/release-drafter@v5
      #   with:
      #     publish: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
